### PR TITLE
ligo-webide: added showcase service

### PR DESCRIPTION
**Pull request by cab404**
ligo team needed a service to showcase their stuff

since it invokes compiler with user data, and I am far from being completely sure that it's secure, i wrapped it in a vm

### CODE REVIEW

**Comment by cab404** [comment]
Oh, maybe I do, and maybe that's the old issue from the gutters of us using serokell-nix

**Comment by cab404** [comment]
Of course it doesn't have ghc caches)

**Comment by notgne2** [comment]
wonder if the mkPipeline stuff will magically fix whatever the terraform issue is 🤔

**Comment by notgne2** [comment]
oh shit

**Comment by notgne2** [comment]
whoops

**Comment by notgne2** [comment]
ok that screwed it up worse

**Pull request merged**
